services:
  db:
    image: postgres:17.4
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # import the dumped sample_db.sql N.B: remove migrations and migrate from below while importing and run first time only while building image
      # - ./sample_database/sample_db.sql:/docker-entrypoint-initdb.d/sample_db.sql
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "6380:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  django_web:
    build: .
    image: quizbit-django_web:1.0.1
    container_name: django-docker
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis-service
    volumes:
      - .:/app
    command: >
      sh -c "while ! nc -z db 5432; do echo '⏳ waiting for PostgreSQL...'; sleep 1; done &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"

volumes:
  postgres_data: