global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'quizbit'
    static_configs:
      - targets: [ "django-docker:8080" ]
        labels:
          application: 'quizbit'

  - job_name: 'redis'
    static_configs:
      - targets: [ "redis-exporter:9121" ]