--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-1.pgdg24.04+1)
-- Dumped by pg_dump version 17.4 (Ubuntu 17.4-1.pgdg24.04+2)

-- Started on 2025-04-15 00:01:18 +06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 42291)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 42290)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 42299)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 42298)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 42285)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 42284)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 42264)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 42263)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 42256)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 42255)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 42239)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 42238)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 42390)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 42331)
-- Name: quiz_choices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_choices (
    id bigint NOT NULL,
    option text NOT NULL,
    is_correct boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.quiz_choices OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 42330)
-- Name: quiz_choices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_choices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_choices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 50754)
-- Name: quiz_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_info (
    id bigint NOT NULL,
    title character varying(250) NOT NULL,
    descriptions text NOT NULL,
    num_questions integer NOT NULL,
    quiz_duration_min integer NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.quiz_info OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 50762)
-- Name: quiz_info_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_info_categories (
    id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    question_category_id bigint NOT NULL
);


ALTER TABLE public.quiz_info_categories OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 42339)
-- Name: quiz_question_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_question_category (
    id bigint NOT NULL,
    name character varying(80) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.quiz_question_category OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 42338)
-- Name: quiz_question_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_question_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_question_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 42347)
-- Name: quiz_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_questions (
    id bigint NOT NULL,
    text text NOT NULL,
    difficulty character varying(15) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.quiz_questions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 42346)
-- Name: quiz_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 50761)
-- Name: quiz_quiz_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_info_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_quiz_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 50753)
-- Name: quiz_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 50782)
-- Name: quiz_quizsession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_quizsession (
    id bigint NOT NULL,
    status character varying(50) NOT NULL,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    score integer,
    quiz_id_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.quiz_quizsession OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 50781)
-- Name: quiz_quizsession_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_quizsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_quizsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 50788)
-- Name: quiz_quizsessionquestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_quizsessionquestion (
    id bigint NOT NULL,
    question_order integer NOT NULL,
    questions_id bigint NOT NULL,
    quiz_session_id bigint NOT NULL
);


ALTER TABLE public.quiz_quizsessionquestion OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 50787)
-- Name: quiz_quizsessionquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_quizsessionquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_quizsessionquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 42247)
-- Name: quiz_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    email character varying(50) NOT NULL,
    name character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    is_admin boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    otp character varying(6),
    is_verified boolean NOT NULL
);


ALTER TABLE public.quiz_users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 42246)
-- Name: quiz_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 42355)
-- Name: quiz_usersolutions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_usersolutions (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    answered_at timestamp with time zone NOT NULL,
    question_id bigint NOT NULL,
    selected_answer_id bigint NOT NULL,
    user_id bigint NOT NULL,
    attempt_type character varying(20) NOT NULL,
    quiz_session_id bigint
);


ALTER TABLE public.quiz_usersolutions OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 42354)
-- Name: quiz_usersolutions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz_usersolutions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_usersolutions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3594 (class 0 OID 42291)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 3596 (class 0 OID 42299)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 3592 (class 0 OID 42285)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add users	6	add_users
22	Can change users	6	change_users
23	Can delete users	6	delete_users
24	Can view users	6	view_users
25	Can add choices	7	add_choices
26	Can change choices	7	change_choices
27	Can delete choices	7	delete_choices
28	Can view choices	7	view_choices
29	Can add question_ category	8	add_question_category
30	Can change question_ category	8	change_question_category
31	Can delete question_ category	8	delete_question_category
32	Can view question_ category	8	view_question_category
33	Can add questions	9	add_questions
34	Can change questions	9	change_questions
35	Can delete questions	9	delete_questions
36	Can view questions	9	view_questions
37	Can add user solutions	10	add_usersolutions
38	Can change user solutions	10	change_usersolutions
39	Can delete user solutions	10	delete_usersolutions
40	Can view user solutions	10	view_usersolutions
41	Can add quiz	11	add_quiz
42	Can change quiz	11	change_quiz
43	Can delete quiz	11	delete_quiz
44	Can view quiz	11	view_quiz
45	Can add quiz session	12	add_quizsession
46	Can change quiz session	12	change_quizsession
47	Can delete quiz session	12	delete_quizsession
48	Can view quiz session	12	view_quizsession
49	Can add quiz session question	13	add_quizsessionquestion
50	Can change quiz session question	13	change_quizsessionquestion
51	Can delete quiz session question	13	delete_quizsessionquestion
52	Can view quiz session question	13	view_quizsessionquestion
\.


--
-- TOC entry 3590 (class 0 OID 42264)
-- Dependencies: 222
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 3588 (class 0 OID 42256)
-- Dependencies: 220
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	quiz	users
7	quiz	choices
8	quiz	question_category
9	quiz	questions
10	quiz	usersolutions
11	quiz	quiz
12	quiz	quizsession
13	quiz	quizsessionquestion
\.


--
-- TOC entry 3584 (class 0 OID 42239)
-- Dependencies: 216
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	quiz	0001_initial	2024-11-18 16:59:00.530704+06
2	contenttypes	0001_initial	2024-11-18 16:59:00.585269+06
3	admin	0001_initial	2024-11-18 16:59:00.718929+06
4	admin	0002_logentry_remove_auto_add	2024-11-18 16:59:00.738842+06
5	admin	0003_logentry_add_action_flag_choices	2024-11-18 16:59:00.767446+06
6	contenttypes	0002_remove_content_type_name	2024-11-18 16:59:00.79802+06
7	auth	0001_initial	2024-11-18 16:59:01.05283+06
8	auth	0002_alter_permission_name_max_length	2024-11-18 16:59:01.090538+06
9	auth	0003_alter_user_email_max_length	2024-11-18 16:59:01.115341+06
10	auth	0004_alter_user_username_opts	2024-11-18 16:59:01.135702+06
11	auth	0005_alter_user_last_login_null	2024-11-18 16:59:01.155409+06
12	auth	0006_require_contenttypes_0002	2024-11-18 16:59:01.169887+06
13	auth	0007_alter_validators_add_error_messages	2024-11-18 16:59:01.191645+06
14	auth	0008_alter_user_username_max_length	2024-11-18 16:59:01.213464+06
15	auth	0009_alter_user_last_name_max_length	2024-11-18 16:59:01.236659+06
16	auth	0010_alter_group_name_max_length	2024-11-18 16:59:01.264697+06
17	auth	0011_update_proxy_permissions	2024-11-18 16:59:01.286786+06
18	auth	0012_alter_user_first_name_max_length	2024-11-18 16:59:01.308603+06
19	quiz	0002_choices_question_category_questions_usersolutions_and_more	2024-11-18 16:59:01.615216+06
20	sessions	0001_initial	2024-11-18 16:59:01.71652+06
21	quiz	0003_users_is_verified_users_otp_alter_users_is_active	2024-12-25 11:40:56.190587+06
22	quiz	0004_remove_users_is_verified	2024-12-25 18:53:01.343885+06
23	quiz	0005_rename_solution_choices_option	2024-12-26 21:40:09.381044+06
24	quiz	0006_users_is_verified_alter_users_email	2024-12-27 10:57:33.351995+06
25	quiz	0007_quiz	2025-01-06 22:37:26.150202+06
26	quiz	0008_alter_quiz_table	2025-01-06 23:06:36.249691+06
27	quiz	0009_quizsession_quizsessionquestion_and_more	2025-02-05 22:49:12.733558+06
28	quiz	0010_quizsession_created_at_alter_quizsession_start_time_and_more	2025-02-07 11:36:45.203251+06
29	quiz	0011_usersolutions_attempt_type_and_more	2025-02-20 19:26:05.801004+06
\.


--
-- TOC entry 3605 (class 0 OID 42390)
-- Dependencies: 237
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
xm01685fl7saanpbj9jinkcq44hhmg2d	.eJxVjEEOwiAQAP_C2RCQ7goevfcNZGFBqgaS0p6MfzckPeh1ZjJv4Wnfit97Wv3C4ipQnH5ZoPhMdQh-UL03GVvd1iXIkcjDdjk3Tq_b0f4NCvUytobBarAJyERnIEMANDEDXxxhRhUmxYms4rNWOGUwJobkyEVAh9qKzxfZyzeJ:1tQnbl:GmWTIlu7cxcekjRDIFj24jPDw8WA6L58zpQztnPUVYQ	2025-01-09 19:08:57.290042+06
spmrba22vjnphkgi7toutnx1y1llkn3s	.eJxVjEEOwiAQAP_C2RCQ7goevfcNZGFBqgaS0p6MfzckPeh1ZjJv4Wnfit97Wv3C4ipQnH5ZoPhMdQh-UL03GVvd1iXIkcjDdjk3Tq_b0f4NCvUytobBarAJyERnIEMANDEDXxxhRhUmxYms4rNWOGUwJobkyEVAh9qKzxfZyzeJ:1tfix1:sMkoFJUoiNKR7J5qHbtdCGaGic-434EPEIp6s9S87aw	2025-02-19 23:12:35.613599+06
\.


--
-- TOC entry 3598 (class 0 OID 42331)
-- Dependencies: 230
-- Data for Name: quiz_choices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_choices (id, option, is_correct, created_at, question_id) FROM stdin;
1	2	f	2024-11-18 23:37:18.496+06	1
2	4	t	2024-11-18 23:37:22.02+06	1
3	5	f	2024-11-18 23:37:23.358+06	1
4	6	f	2024-11-18 23:37:24.477+06	1
5	Au	t	2024-11-18 23:39:45.427+06	2
6	Gu	f	2024-11-18 23:39:47.668+06	2
7	Gd	f	2024-11-18 23:39:48.744+06	2
8	Gl	f	2024-11-18 23:39:49.595+06	2
9	2	t	2024-11-20 00:35:43.12+06	3
10	4	f	2024-11-20 00:35:56.426+06	3
11	0	f	2024-11-20 00:35:59.962+06	3
12	1	f	2024-11-20 00:36:04.18+06	3
25	C6H12O6	t	2025-01-05 18:51:58.80479+06	7
47	O(n^2)	f	2025-01-05 18:51:58.80479+06	12
46	O(n)	f	2025-01-05 18:51:58.80479+06	12
61	5	t	2025-01-05 18:51:58.80479+06	16
37	Central Processing Unit	t	2025-01-05 18:51:58.80479+06	10
39	Compute Power Unit	f	2025-01-05 18:51:58.80479+06	10
18	Monaco	f	2025-01-05 18:51:58.80479+06	5
53	1789	t	2025-01-05 18:51:58.80479+06	14
33	Mitochondria	t	2025-01-05 18:51:58.80479+06	9
69	Brazil	t	2025-01-05 18:51:58.80479+06	18
35	Ribosome	f	2025-01-05 18:51:58.80479+06	9
30	Rutherford	f	2025-01-05 18:51:58.80479+06	8
49	Augustus	t	2025-01-05 18:51:58.80479+06	13
56	1815	f	2025-01-05 18:51:58.80479+06	14
27	CO2	f	2025-01-05 18:51:58.80479+06	7
19	Malta	f	2025-01-05 18:51:58.80479+06	5
38	Control Process Unit	f	2025-01-05 18:51:58.80479+06	10
59	Potsdam Agreement	f	2025-01-05 18:51:58.80479+06	15
68	Rio de Janeiro	t	2025-01-05 18:51:58.80479+06	17
45	O(log n)	t	2025-01-05 18:51:58.80479+06	12
63	7	f	2025-01-05 18:51:58.80479+06	16
62	6	f	2025-01-05 18:51:58.80479+06	16
20	Liechtenstein	f	2025-01-05 18:51:58.80479+06	5
29	J.J. Thomson	t	2025-01-05 18:51:58.80479+06	8
48	O(1)	f	2025-01-05 18:51:58.80479+06	12
31	Bohr	f	2025-01-05 18:51:58.80479+06	8
60	Treaty of Tordesillas	f	2025-01-05 18:51:58.80479+06	15
58	Treaty of Paris	f	2025-01-05 18:51:58.80479+06	15
28	NaCl	f	2025-01-05 18:51:58.80479+06	7
15	Beijing	f	2025-01-05 18:51:58.80479+06	4
13	Tokyo	t	2025-01-05 18:51:58.80479+06	4
44	Tim Berners-Lee	f	2025-01-05 18:51:58.80479+06	11
42	Alan Turing	f	2025-01-05 18:51:58.80479+06	11
26	H2O	f	2025-01-05 18:51:58.80479+06	7
14	Seoul	f	2025-01-05 18:51:58.80479+06	4
16	Bangkok	f	2025-01-05 18:51:58.80479+06	4
21	206	t	2025-01-05 18:51:58.80479+06	6
54	1776	f	2025-01-05 18:51:58.80479+06	14
57	Treaty of Versailles	t	2025-01-05 18:51:58.80479+06	15
67	China	f	2025-01-05 18:51:58.80479+06	17
66	USA	f	2025-01-05 18:51:58.80479+06	17
51	Nero	f	2025-01-05 18:51:58.80479+06	13
36	Lysosome	f	2025-01-05 18:51:58.80479+06	9
50	Julius Caesar	f	2025-01-05 18:51:58.80479+06	13
41	Charles Babbage	t	2025-01-05 18:51:58.80479+06	11
55	1804	f	2025-01-05 18:51:58.80479+06	14
43	Bill Gates	f	2025-01-05 18:51:58.80479+06	11
40	Central Power Unit	f	2025-01-05 18:51:58.80479+06	10
34	Nucleus	f	2025-01-05 18:51:58.80479+06	9
23	180	f	2025-01-05 18:51:58.80479+06	6
64	4	f	2025-01-05 18:51:58.80479+06	16
52	Marcus Aurelius	f	2025-01-05 18:51:58.80479+06	13
65	Brazil	f	2025-01-05 18:51:58.80479+06	17
24	250	f	2025-01-05 18:51:58.80479+06	6
22	210	f	2025-01-05 18:51:58.80479+06	6
17	Vatican City	t	2025-01-05 18:51:58.80479+06	5
32	Einstein	f	2025-01-05 18:51:58.80479+06	8
71	Italy	f	2025-01-05 18:51:58.80479+06	18
70	Germany	f	2025-01-05 18:51:58.80479+06	18
72	Argentina	f	2025-01-05 18:51:58.80479+06	18
\.


--
-- TOC entry 3607 (class 0 OID 50754)
-- Dependencies: 239
-- Data for Name: quiz_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_info (id, title, descriptions, num_questions, quiz_duration_min, is_active) FROM stdin;
2	Chemical Bonds	Basic chemical bonding concepts	7	50	t
1	Newton's Laws	 Test on Newton's Laws of Motion	5	50	t
\.


--
-- TOC entry 3609 (class 0 OID 50762)
-- Dependencies: 241
-- Data for Name: quiz_info_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_info_categories (id, quiz_id, question_category_id) FROM stdin;
1	1	1
2	1	10
3	2	3
4	2	5
5	1	5
\.


--
-- TOC entry 3600 (class 0 OID 42339)
-- Dependencies: 232
-- Data for Name: quiz_question_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_question_category (id, name, description, created_at) FROM stdin;
1	Math	mathematics	2024-11-18 23:08:38.964+06
2	GS	general science	2024-11-18 23:08:51.939+06
3	Chemistry	science	2024-11-18 23:09:05.872+06
4	General Knowledge	Trivia and general facts	2025-01-05 18:42:26.14279+06
5	Science	Physics, Chemistry, Biology	2025-01-05 18:42:26.14279+06
6	Technology	IT, Software, and Engineering	2025-01-05 18:42:26.14279+06
7	History	Historical events and figures	2025-01-05 18:42:26.14279+06
8	Sports	Sports and athletics	2025-01-05 18:42:26.14279+06
10	Physics	physics subject	2025-02-12 05:02:44.383+06
\.


--
-- TOC entry 3602 (class 0 OID 42347)
-- Dependencies: 234
-- Data for Name: quiz_questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_questions (id, text, difficulty, is_active, created_at, category_id) FROM stdin;
2	What is the symbol for Gold?	medium	t	2024-11-18 23:09:45.767+06	3
3	What is log(100) = ?	hard	t	2024-11-18 23:10:19.171+06	1
1	What is 1 + 3 = ?	easy	t	2024-11-18 23:08:09+06	1
4	What is the capital of Japan?	easy	t	2025-01-05 18:49:16.432781+06	1
5	Which is the smallest country in the world?	medium	t	2025-01-05 18:49:16.432781+06	1
6	How many bones are \tthere in the human body?	hard	t	2025-01-05 18:49:16.432781+06	1
7	What is the chemical formula of glucose?	easy	t	2025-01-05 18:49:16.432781+06	2
8	Who discovered the electron?	medium	t	2025-01-05 18:49:16.432781+06	2
9	What is the powerhouse of the cell?	hard	t	2025-01-05 18:49:16.432781+06	2
10	What does CPU stand for?	easy	t	2025-01-05 18:49:16.432781+06	3
11	Who is known as the father of the computer?	medium	t	2025-01-05 18:49:16.432781+06	3
12	What is the time complexity of binary search?	hard	t	2025-01-05 18:49:16.432781+06	3
13	Who was the first Emperor of Rome?	easy	t	2025-01-05 18:49:16.432781+06	4
14	When did the French Revolution start?	medium	t	2025-01-05 18:49:16.432781+06	4
15	Which treaty ended World War I?	hard	t	2025-01-05 18:49:16.432781+06	4
17	Which country hosted the 2016 Summer Olympics?	medium	t	2025-01-05 18:49:16.432781+06	8
16	How many players are in a basketball team?	easy	t	2025-01-05 18:49:16.432781+06	8
18	Which country has won the most FIFA World Cup titles?	hard	t	2025-01-05 18:49:16.432781+06	8
\.


--
-- TOC entry 3611 (class 0 OID 50782)
-- Dependencies: 243
-- Data for Name: quiz_quizsession; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_quizsession (id, status, start_time, end_time, score, quiz_id_id, user_id, created_at) FROM stdin;
1	in_progress	2025-02-07 07:03:33.459+06	\N	\N	1	23	2025-02-07 07:03:00+06
2	not_started	\N	\N	\N	2	23	2025-02-07 11:52:56.140467+06
27	not_started	\N	\N	\N	2	23	2025-02-12 22:33:09.429198+06
28	in_progress	2025-02-12 22:42:43.64607+06	2025-02-12 22:46:43.64607+06	\N	2	23	2025-02-12 22:42:43.60295+06
49	expired	2025-03-03 17:07:57.4512+06	2025-03-03 17:14:57.4512+06	\N	1	10	2025-03-03 17:07:57.385264+06
29	expired	2025-02-16 21:12:52.484022+06	2025-02-16 21:15:52.484022+06	\N	1	10	2025-02-16 21:12:52.432833+06
30	expired	2025-02-23 22:46:05.563103+06	2025-02-23 22:49:05.563103+06	\N	1	10	2025-02-23 22:46:05.502239+06
31	expired	2025-02-23 22:47:24.65853+06	2025-02-23 22:50:24.65853+06	\N	1	10	2025-02-23 22:47:24.616966+06
50	expired	2025-03-03 21:12:56.872845+06	2025-03-03 21:19:56.872845+06	\N	1	10	2025-03-03 21:12:56.828594+06
32	expired	2025-02-23 23:04:33.578991+06	2025-02-23 23:07:33.578991+06	\N	1	10	2025-02-23 23:04:33.52494+06
33	expired	2025-02-23 23:19:08.931199+06	2025-02-23 23:22:08.931199+06	\N	1	10	2025-02-23 23:19:08.882932+06
34	expired	2025-02-23 23:19:17.262922+06	2025-02-23 23:22:17.262922+06	\N	1	10	2025-02-23 23:19:17.22183+06
51	expired	2025-03-03 21:44:43.821323+06	2025-03-03 21:51:43.821323+06	\N	1	10	2025-03-03 21:44:43.770013+06
35	expired	2025-02-23 23:37:19.716527+06	2025-02-23 23:40:19.716527+06	\N	1	10	2025-02-23 23:37:19.673767+06
36	expired	2025-02-24 20:20:45.085776+06	2025-02-24 20:23:45.085776+06	\N	1	10	2025-02-24 20:20:45.034959+06
70	expired	2025-04-14 00:30:31.136958+06	2025-04-14 01:20:31.136958+06	\N	1	10	2025-04-14 00:30:31.091059+06
37	expired	2025-02-24 21:03:21.800511+06	2025-02-24 21:06:21.800511+06	\N	1	10	2025-02-24 21:03:21.758516+06
52	expired	2025-03-03 21:54:56.263045+06	2025-03-03 22:01:56.263045+06	\N	1	10	2025-03-03 21:54:56.219888+06
38	expired	2025-02-24 21:07:11.683276+06	2025-02-24 21:10:11.683276+06	\N	1	10	2025-02-24 21:07:11.642571+06
39	expired	2025-02-24 22:21:40.362366+06	2025-02-24 22:28:40.362366+06	\N	1	10	2025-02-24 22:21:40.320588+06
40	expired	2025-02-24 22:42:42.08793+06	2025-02-24 22:49:42.08793+06	\N	1	10	2025-02-24 22:42:41.774804+06
53	expired	2025-03-03 22:15:56.557367+06	2025-03-03 22:35:56.557367+06	\N	1	10	2025-03-03 22:15:56.509642+06
41	expired	2025-02-25 20:47:16.650216+06	2025-02-25 20:54:16.650216+06	\N	1	10	2025-02-25 20:47:16.580262+06
42	expired	2025-02-25 22:17:57.689605+06	2025-02-25 22:24:57.689605+06	\N	1	10	2025-02-25 22:17:57.646137+06
71	in_progress	2025-04-14 01:40:09.095013+06	2025-04-14 02:30:09.095013+06	\N	1	10	2025-04-14 01:40:09.05333+06
43	expired	2025-02-25 22:26:15.236958+06	2025-02-25 22:33:15.236958+06	\N	1	10	2025-02-25 22:26:15.194629+06
54	expired	2025-03-03 22:44:07.509416+06	2025-03-03 23:04:07.509416+06	\N	1	10	2025-03-03 22:44:07.437328+06
44	expired	2025-02-25 22:37:18.716092+06	2025-02-25 22:44:18.716092+06	\N	1	10	2025-02-25 22:37:18.673195+06
45	completed	2025-02-25 23:34:02.027699+06	2025-02-25 23:41:02.027699+06	\N	1	10	2025-02-25 23:34:01.984854+06
46	expired	2025-02-26 19:22:40.822509+06	2025-02-26 19:29:40.822509+06	\N	1	10	2025-02-26 19:22:40.75143+06
55	expired	2025-03-03 23:34:16.031689+06	2025-03-03 23:54:16.031689+06	\N	1	10	2025-03-03 23:34:15.976973+06
47	expired	2025-02-26 23:17:55.533163+06	2025-02-26 23:24:55.533163+06	\N	1	10	2025-02-26 23:17:55.491858+06
48	expired	2025-02-26 23:25:50.462112+06	2025-02-26 23:32:50.462112+06	\N	1	10	2025-02-26 23:25:50.421507+06
56	completed	2025-03-04 00:00:37.222797+06	2025-03-04 00:50:37.222797+06	\N	1	10	2025-03-04 00:00:37.179142+06
58	in_progress	2025-03-17 17:48:45.091995+06	2025-03-17 18:38:45.091995+06	\N	2	10	2025-03-17 17:48:45.054649+06
57	completed	2025-03-17 17:25:09.235736+06	2025-03-17 18:15:09.235736+06	\N	1	10	2025-03-17 17:25:09.159496+06
59	expired	2025-03-17 17:53:51.522158+06	2025-03-17 18:43:51.522158+06	\N	1	10	2025-03-17 17:53:51.482148+06
60	expired	2025-03-17 23:07:15.067719+06	2025-03-17 23:57:15.067719+06	\N	1	10	2025-03-17 23:07:15.020703+06
61	expired	2025-03-22 18:51:37.90514+06	2025-03-22 19:41:37.90514+06	\N	1	10	2025-03-22 18:51:37.820883+06
62	expired	2025-04-08 22:10:49.2386+06	2025-04-08 23:00:49.2386+06	\N	1	10	2025-04-08 22:10:49.161579+06
63	expired	2025-04-11 14:03:39.407754+06	2025-04-11 14:53:39.407754+06	\N	1	10	2025-04-11 14:03:39.301913+06
64	expired	2025-04-11 23:29:14.495327+06	2025-04-12 00:19:14.495327+06	\N	1	10	2025-04-11 23:29:14.40874+06
65	completed	2025-04-12 21:49:15.123759+06	2025-04-12 22:39:15.123759+06	\N	1	10	2025-04-12 21:49:15.025734+06
66	completed	2025-04-13 21:59:38.845718+06	2025-04-13 22:49:38.845718+06	\N	1	10	2025-04-13 21:59:38.738276+06
67	expired	2025-04-13 22:00:20.064696+06	2025-04-13 22:50:20.064696+06	\N	1	10	2025-04-13 22:00:20.020013+06
68	expired	2025-04-13 23:24:26.286587+06	2025-04-14 00:14:26.286587+06	\N	1	10	2025-04-13 23:24:26.244963+06
69	completed	2025-04-14 00:25:18.849995+06	2025-04-14 01:15:18.849995+06	\N	1	10	2025-04-14 00:25:18.805974+06
\.


--
-- TOC entry 3613 (class 0 OID 50788)
-- Dependencies: 245
-- Data for Name: quiz_quizsessionquestion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_quizsessionquestion (id, question_order, questions_id, quiz_session_id) FROM stdin;
1	0	10	28
2	1	12	28
3	2	11	28
4	3	2	28
5	0	1	29
6	1	6	29
7	2	4	29
8	3	5	29
9	4	3	29
10	0	4	30
11	1	6	30
12	2	3	30
13	3	5	30
14	4	1	30
15	0	1	31
16	1	6	31
17	2	3	31
18	3	5	31
19	4	4	31
20	0	3	32
21	1	1	32
22	2	5	32
23	3	4	32
24	4	6	32
25	0	4	33
26	1	6	33
27	2	1	33
28	3	5	33
29	4	3	33
30	0	3	34
31	1	6	34
32	2	5	34
33	3	4	34
34	4	1	34
35	0	1	35
36	1	3	35
37	2	4	35
38	3	5	35
39	4	6	35
40	0	6	36
41	1	3	36
42	2	1	36
43	3	5	36
44	4	4	36
45	0	3	37
46	1	4	37
47	2	6	37
48	3	1	37
49	4	5	37
50	0	1	38
51	1	6	38
52	2	4	38
53	3	5	38
54	4	3	38
55	0	3	39
56	1	6	39
57	2	1	39
58	3	5	39
59	4	4	39
60	0	3	40
61	1	5	40
62	2	6	40
63	3	1	40
64	4	4	40
65	0	1	41
66	1	3	41
67	2	4	41
68	3	5	41
69	4	6	41
70	0	3	42
71	1	5	42
72	2	4	42
73	3	6	42
74	4	1	42
75	0	5	43
76	1	6	43
77	2	4	43
78	3	3	43
79	4	1	43
80	0	4	44
81	1	5	44
82	2	6	44
83	3	3	44
84	4	1	44
85	0	4	45
86	1	5	45
87	2	6	45
88	3	1	45
89	4	3	45
90	0	5	46
91	1	6	46
92	2	1	46
93	3	3	46
94	4	4	46
95	0	1	47
96	1	5	47
97	2	6	47
98	3	3	47
99	4	4	47
100	0	1	48
101	1	3	48
102	2	4	48
103	3	6	48
104	4	5	48
105	0	1	49
106	1	3	49
107	2	4	49
108	3	5	49
109	4	6	49
110	0	6	50
111	1	3	50
112	2	4	50
113	3	5	50
114	4	1	50
115	0	5	51
116	1	1	51
117	2	6	51
118	3	3	51
119	4	4	51
120	0	3	52
121	1	5	52
122	2	4	52
123	3	6	52
124	4	1	52
125	0	1	53
126	1	6	53
127	2	5	53
128	3	4	53
129	4	3	53
130	0	3	54
131	1	6	54
132	2	5	54
133	3	4	54
134	4	1	54
135	0	5	55
136	1	4	55
137	2	1	55
138	3	3	55
139	4	6	55
140	0	4	56
141	1	3	56
142	2	5	56
143	3	1	56
144	4	6	56
145	0	1	57
146	1	5	57
147	2	6	57
148	3	3	57
149	4	4	57
150	0	12	58
151	1	2	58
152	2	10	58
153	3	11	58
154	0	1	59
155	1	6	59
156	2	4	59
157	3	5	59
158	4	3	59
159	0	6	60
160	1	3	60
161	2	4	60
162	3	5	60
163	4	1	60
164	0	1	61
165	1	3	61
166	2	4	61
167	3	5	61
168	4	6	61
169	0	1	62
170	1	4	62
171	2	6	62
172	3	5	62
173	4	3	62
174	0	5	63
175	1	3	63
176	2	4	63
177	3	1	63
178	4	6	63
179	0	1	64
180	1	3	64
181	2	4	64
182	3	6	64
183	4	5	64
184	0	1	65
185	1	5	65
186	2	3	65
187	3	4	65
188	4	6	65
189	0	4	66
190	1	3	66
191	2	6	66
192	3	5	66
193	4	1	66
194	0	3	67
195	1	1	67
196	2	4	67
197	3	5	67
198	4	6	67
199	0	3	68
200	1	4	68
201	2	5	68
202	3	6	68
203	4	1	68
204	0	3	69
205	1	5	69
206	2	1	69
207	3	6	69
208	4	4	69
209	0	3	70
210	1	5	70
211	2	4	70
212	3	1	70
213	4	6	70
214	0	4	71
215	1	6	71
216	2	5	71
217	3	1	71
218	4	3	71
\.


--
-- TOC entry 3586 (class 0 OID 42247)
-- Dependencies: 218
-- Data for Name: quiz_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_users (id, password, last_login, email, name, is_active, is_admin, created_at, modified, otp, is_verified) FROM stdin;
1	pbkdf2_sha256$600000$SUsTgGqCdvFuNNn7jzcpAU$UQWrPsF9E/EeB18xa2jKfVqBALdeh1ipm2OEYlowWSY=	\N	ab1@gmail.com	Seyam	t	f	2024-11-18 17:00:19.400022+06	2024-11-18 17:00:19.400046+06	\N	f
2	pbkdf2_sha256$600000$yOB7FxuQg6sTUIhSPZmKh3$F6QRQ0Trv3+EgXZ7GGClGMTXIaUQD6pIAczRM0lJCDg=	\N	ab2@gmail.com	Seyam	t	f	2024-11-18 17:00:35.437092+06	2024-11-18 17:00:35.437114+06	\N	f
3	pbkdf2_sha256$600000$qbMAQvE2gcxZew01xPgDoo$20EyCxC8M0iH87oiKxEghnEJr8Xd4tRgMj+FRSQ+zQs=	\N	ab3@gmail.com	Abir	t	f	2024-11-18 17:01:14.45627+06	2024-11-18 17:01:14.456294+06	\N	f
4	pbkdf2_sha256$600000$UtNyqgVFjVwvYGZLAcLPgh$YSz/u0qS52mdtqEdMdjtLkgiSUyl/e4Zz9y1A5Hn4xQ=	\N	shahed@gmail.com	Shahed Afridi	t	f	2024-11-19 19:58:22.974111+06	2024-11-19 19:58:22.974129+06	\N	f
5	pbkdf2_sha256$600000$QdcmEpRC9UF8rEOUFOU0De$jnTkvGN9wxYAdn+V07oTR12O0LBOQRpuSYMwfjeDx7o=	\N	test@gmail.com	Afridi	t	f	2024-11-19 20:25:32.19095+06	2024-11-19 20:25:32.191375+06	\N	f
23	pbkdf2_sha256$600000$9P3D7b6V39KOSsjD3ybAVX$SrE0NVl9Af06maXXb6uH9wpANEtEQrA53HnBHbhIbAs=	\N	seyamsadlil@gmail.com	seyam 435	t	f	2024-12-27 11:00:31.043472+06	2024-12-27 20:40:47.187446+06	\N	t
24	pbkdf2_sha256$600000$s0vfoJuVlukDfTvFrxTxNm$InC3AjWcW7zT0P3FXAeWBoogA9F34JY3HYzP6P5Bt3c=	\N	sh4568@gmail.com	Shahed Afridi	f	f	2024-12-31 19:15:15.747353+06	2024-12-31 19:15:42.438279+06	8606	f
6	pbkdf2_sha256$600000$VyAMOPUSKggOx0H1aqnn0p$5j9SlouuuPhUkuYqPHENzAfq14J5nHyP6XVAD84Pjp8=	2025-02-05 23:12:35.604879+06	admin@gmail.com	admin	t	t	2024-12-24 21:21:00.065869+06	2024-12-24 21:21:00.074152+06	\N	f
10	pbkdf2_sha256$600000$WLabsQZVw4YPb0YfZJMOQJ$2ZRnvWIbF9Y6Ki595umNdfnGKk2kKU0PFzleA3+j488=	\N	seyamsadlil647@gmail.com	Seyam 12	t	f	2024-12-25 15:00:25.447032+06	2024-12-25 15:00:29.522384+06	1419	t
\.


--
-- TOC entry 3604 (class 0 OID 42355)
-- Dependencies: 236
-- Data for Name: quiz_usersolutions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_usersolutions (id, is_correct, answered_at, question_id, selected_answer_id, user_id, attempt_type, quiz_session_id) FROM stdin;
9	f	2024-11-19 20:25:47.796034+06	1	3	5	practice	\N
10	t	2024-11-19 20:31:38.204699+06	3	9	5	practice	\N
11	f	2025-01-01 20:38:51.633627+06	1	3	23	practice	\N
12	f	2025-02-23 19:15:28.309964+06	1	3	10	quiz	1
13	f	2025-02-23 19:16:53.356117+06	1	3	10	quiz	1
14	f	2025-02-23 19:19:53.696512+06	1	4	10	quiz	1
15	t	2025-02-23 19:20:21.678952+06	1	2	10	quiz	1
16	t	2025-02-23 19:33:01.309514+06	1	2	10	quiz	1
17	t	2025-02-23 19:39:07.129644+06	1	2	10	quiz	1
18	t	2025-02-23 19:52:31.055853+06	1	2	10	quiz	29
19	t	2025-02-23 23:34:59.556284+06	1	2	10	quiz	1
20	t	2025-02-23 23:38:58.450703+06	1	2	10	quiz	35
21	f	2025-02-23 23:41:37.767918+06	3	10	10	quiz	35
22	f	2025-02-23 23:42:03.534846+06	2	7	10	quiz	35
23	f	2025-02-23 23:42:14.990783+06	2	7	10	quiz	35
24	f	2025-02-24 19:49:29.0276+06	2	7	10	quiz	35
25	f	2025-02-24 20:21:04.784488+06	2	7	10	quiz	35
26	f	2025-02-24 20:28:43.330549+06	2	7	10	quiz	35
27	f	2025-02-24 20:29:02.73432+06	2	7	10	quiz	35
28	f	2025-02-24 20:29:29.321242+06	2	7	10	quiz	36
29	f	2025-02-24 20:29:41.139422+06	2	7	10	quiz	36
30	f	2025-02-24 20:30:15.939619+06	1	3	10	quiz	36
31	f	2025-02-24 20:30:28.930758+06	1	3	10	quiz	36
32	f	2025-02-24 21:07:25.895859+06	1	3	10	quiz	38
33	f	2025-02-24 22:44:26.474802+06	3	12	10	quiz	40
34	f	2025-02-24 22:46:03.531979+06	5	30	10	quiz	40
35	t	2025-02-24 22:46:24.327891+06	1	2	10	quiz	40
36	f	2025-02-24 22:47:00.216699+06	4	28	10	quiz	40
37	f	2025-02-24 22:47:31.953352+06	6	36	10	quiz	40
38	f	2025-02-25 20:47:34.543443+06	6	36	10	quiz	41
39	f	2025-02-25 20:48:23.213192+06	6	36	10	quiz	41
40	f	2025-02-25 20:49:40.157886+06	6	36	10	quiz	41
41	f	2025-02-25 20:49:46.504712+06	6	36	10	quiz	41
42	f	2025-02-25 22:18:02.188359+06	6	36	10	quiz	42
43	f	2025-02-25 22:18:11.125901+06	6	36	10	quiz	42
44	f	2025-02-25 22:26:23.218644+06	6	36	10	quiz	43
45	f	2025-02-25 22:26:30.326131+06	6	36	10	quiz	43
46	f	2025-02-25 22:32:19.501497+06	6	36	10	quiz	43
47	f	2025-02-25 22:32:55.774773+06	6	36	10	quiz	43
48	f	2025-02-25 22:33:00.246494+06	6	36	10	quiz	43
49	f	2025-02-25 22:33:10.699038+06	6	36	10	quiz	43
50	f	2025-02-25 22:37:25.312803+06	6	36	10	quiz	44
51	f	2025-02-25 22:37:58.578395+06	6	36	10	quiz	44
52	f	2025-02-25 22:38:01.714168+06	6	36	10	quiz	44
53	f	2025-02-25 22:38:04.039117+06	6	36	10	quiz	44
54	f	2025-02-25 22:38:14.841703+06	6	36	10	quiz	44
55	f	2025-02-25 22:38:21.221684+06	6	36	10	quiz	44
56	f	2025-02-25 22:38:42.24193+06	6	36	10	quiz	44
57	f	2025-02-25 23:34:09.078845+06	6	36	10	quiz	45
58	f	2025-02-25 23:34:15.65499+06	6	36	10	quiz	45
59	f	2025-02-25 23:34:17.591001+06	6	36	10	quiz	45
60	f	2025-02-25 23:34:18.972166+06	6	36	10	quiz	45
61	f	2025-02-25 23:34:43.878077+06	6	36	10	quiz	45
62	f	2025-02-26 19:27:46.908691+06	1	4	10	quiz	46
63	f	2025-02-26 19:28:06.828762+06	1	4	10	quiz	46
64	t	2025-02-26 19:29:17.150165+06	1	2	10	quiz	46
65	t	2025-03-03 17:10:54.637653+06	3	9	10	quiz	49
66	t	2025-03-03 17:11:05.03465+06	3	9	10	quiz	49
67	f	2025-03-04 00:00:58.169279+06	5	18	10	quiz	56
68	f	2025-03-04 00:00:58.182742+06	4	15	10	quiz	56
69	f	2025-03-04 00:00:58.195231+06	1	1	10	quiz	56
70	t	2025-03-04 00:00:58.208138+06	3	9	10	quiz	56
71	t	2025-03-04 00:00:58.222942+06	6	21	10	quiz	56
72	f	2025-03-17 17:52:14.614198+06	5	18	10	quiz	57
73	f	2025-03-17 17:52:14.631796+06	4	15	10	quiz	57
74	f	2025-03-17 17:52:14.645163+06	1	1	10	quiz	57
75	t	2025-03-17 17:52:14.658363+06	3	9	10	quiz	57
76	f	2025-03-17 17:52:14.672223+06	6	22	10	quiz	57
77	t	2025-03-22 19:15:11.492548+06	1	2	10	quiz	61
78	f	2025-03-22 19:15:11.505088+06	3	10	10	quiz	61
79	f	2025-03-22 19:15:11.516158+06	4	15	10	quiz	61
80	t	2025-03-22 19:15:37.807331+06	1	2	10	quiz	61
81	f	2025-03-22 19:15:37.818626+06	3	10	10	quiz	61
82	f	2025-03-22 19:15:37.830167+06	4	15	10	quiz	61
83	t	2025-03-22 19:20:49.403067+06	1	2	10	quiz	61
84	f	2025-03-22 19:20:49.424235+06	3	10	10	quiz	61
85	f	2025-03-22 19:20:49.435169+06	4	15	10	quiz	61
86	t	2025-03-22 19:21:18.19156+06	1	2	10	quiz	61
87	f	2025-03-22 19:21:18.202677+06	3	10	10	quiz	61
88	f	2025-03-22 19:21:18.212613+06	4	15	10	quiz	61
89	t	2025-03-22 19:24:11.088026+06	1	2	10	quiz	61
90	f	2025-03-22 19:24:11.098875+06	3	10	10	quiz	61
91	f	2025-03-22 19:24:11.110534+06	4	15	10	quiz	61
92	t	2025-03-22 19:39:36.790936+06	1	2	10	quiz	61
93	f	2025-03-22 19:39:36.806369+06	3	10	10	quiz	61
94	f	2025-03-22 19:39:36.816692+06	4	15	10	quiz	61
95	t	2025-04-08 22:11:06.74398+06	1	2	10	quiz	62
96	f	2025-04-08 22:11:06.76444+06	3	10	10	quiz	62
97	f	2025-04-08 22:11:06.776419+06	4	15	10	quiz	62
98	t	2025-04-08 22:23:24.637801+06	1	2	10	quiz	62
99	f	2025-04-08 22:23:24.651531+06	3	10	10	quiz	62
100	f	2025-04-08 22:23:24.661536+06	4	15	10	quiz	62
101	t	2025-04-08 22:25:42.386423+06	1	2	10	quiz	62
102	f	2025-04-08 22:25:42.398537+06	3	10	10	quiz	62
103	f	2025-04-08 22:25:42.409694+06	4	15	10	quiz	62
104	t	2025-04-08 22:54:41.322443+06	1	2	10	quiz	62
105	f	2025-04-08 22:56:00.929905+06	3	10	10	quiz	62
106	f	2025-04-08 22:56:16.486348+06	4	15	10	quiz	62
107	t	2025-04-08 22:59:04.670273+06	1	2	10	quiz	62
108	f	2025-04-08 22:59:06.874383+06	3	10	10	quiz	62
109	f	2025-04-08 22:59:08.281622+06	4	15	10	quiz	62
110	t	2025-04-11 14:06:37.512535+06	1	2	10	quiz	63
111	f	2025-04-11 14:06:58.106685+06	3	10	10	quiz	63
112	f	2025-04-11 14:07:11.226784+06	4	15	10	quiz	63
113	t	2025-04-11 14:10:27.432607+06	1	2	10	quiz	63
114	f	2025-04-11 14:10:27.443134+06	3	10	10	quiz	63
115	f	2025-04-11 14:10:27.454248+06	4	15	10	quiz	63
116	t	2025-04-11 23:39:58.668832+06	1	2	10	quiz	64
117	f	2025-04-11 23:39:58.715092+06	3	10	10	quiz	64
118	f	2025-04-11 23:39:58.754552+06	4	15	10	quiz	64
119	t	2025-04-11 23:45:23.739523+06	1	2	10	quiz	64
120	f	2025-04-11 23:45:23.751625+06	3	10	10	quiz	64
121	f	2025-04-11 23:45:23.762805+06	4	15	10	quiz	64
122	t	2025-04-11 23:47:03.99394+06	1	2	10	quiz	64
123	f	2025-04-11 23:47:04.004592+06	3	10	10	quiz	64
124	f	2025-04-11 23:47:04.014879+06	4	15	10	quiz	64
125	t	2025-04-11 23:47:33.133015+06	1	2	10	quiz	64
126	f	2025-04-11 23:47:33.144276+06	3	10	10	quiz	64
127	f	2025-04-11 23:47:33.153759+06	4	15	10	quiz	64
128	f	2025-04-11 23:47:33.173976+06	5	19	10	quiz	64
129	f	2025-04-11 23:47:33.184966+06	6	24	10	quiz	64
130	t	2025-04-11 23:49:43.818537+06	1	2	10	quiz	64
131	f	2025-04-11 23:49:43.830304+06	3	10	10	quiz	64
132	f	2025-04-11 23:49:43.840507+06	4	15	10	quiz	64
133	f	2025-04-11 23:49:43.850733+06	5	19	10	quiz	64
134	f	2025-04-11 23:49:43.862347+06	6	24	10	quiz	64
135	t	2025-04-11 23:50:02.054306+06	1	2	10	quiz	64
136	f	2025-04-11 23:50:02.066262+06	3	10	10	quiz	64
137	f	2025-04-11 23:50:02.07636+06	4	15	10	quiz	64
138	f	2025-04-11 23:50:02.086615+06	5	19	10	quiz	64
139	f	2025-04-11 23:50:02.097958+06	6	24	10	quiz	64
140	t	2025-04-12 21:49:34.371861+06	1	2	10	quiz	65
141	f	2025-04-12 21:49:34.389341+06	3	10	10	quiz	65
142	f	2025-04-12 21:49:34.400285+06	4	15	10	quiz	65
143	f	2025-04-12 21:49:34.410917+06	5	19	10	quiz	65
144	f	2025-04-12 21:49:34.453581+06	6	24	10	quiz	65
145	t	2025-04-13 21:59:59.373394+06	1	2	10	quiz	66
146	f	2025-04-13 21:59:59.391193+06	3	10	10	quiz	66
147	f	2025-04-13 21:59:59.401869+06	4	15	10	quiz	66
148	f	2025-04-13 21:59:59.413298+06	5	19	10	quiz	66
149	f	2025-04-13 21:59:59.425621+06	6	24	10	quiz	66
150	f	2025-04-13 22:00:56.322744+06	3	10	10	quiz	67
151	f	2025-04-13 22:00:56.336864+06	4	15	10	quiz	67
152	f	2025-04-13 22:00:56.34996+06	5	19	10	quiz	67
153	f	2025-04-13 22:00:56.362874+06	6	24	10	quiz	67
154	t	2025-04-13 22:02:05.47298+06	1	2	10	quiz	67
155	f	2025-04-13 22:02:05.484083+06	3	10	10	quiz	67
156	f	2025-04-13 22:02:05.496206+06	4	15	10	quiz	67
157	f	2025-04-13 22:02:05.506852+06	5	19	10	quiz	67
158	f	2025-04-13 22:02:05.517756+06	6	24	10	quiz	67
159	t	2025-04-13 22:02:31.449581+06	1	2	10	quiz	67
160	f	2025-04-13 22:02:31.462324+06	3	10	10	quiz	67
161	f	2025-04-13 22:02:31.472309+06	4	15	10	quiz	67
162	f	2025-04-13 22:02:31.483217+06	5	19	10	quiz	67
163	f	2025-04-13 22:02:31.494315+06	6	24	10	quiz	67
164	t	2025-04-13 22:05:06.818292+06	1	2	10	quiz	67
165	f	2025-04-13 22:05:06.830747+06	3	10	10	quiz	67
166	f	2025-04-13 22:05:06.843178+06	4	15	10	quiz	67
167	f	2025-04-13 22:05:06.856231+06	5	19	10	quiz	67
168	f	2025-04-13 22:05:06.868085+06	6	24	10	quiz	67
169	f	2025-04-13 22:46:46.119667+06	1	3	10	quiz	67
170	f	2025-04-13 22:46:46.135727+06	3	10	10	quiz	67
171	f	2025-04-13 22:46:46.148598+06	4	15	10	quiz	67
172	f	2025-04-13 22:46:46.162199+06	5	19	10	quiz	67
173	f	2025-04-13 22:46:46.177072+06	6	24	10	quiz	67
174	f	2025-04-14 00:30:16.277091+06	1	3	10	quiz	69
175	f	2025-04-14 00:30:16.293431+06	3	10	10	quiz	69
176	f	2025-04-14 00:30:16.308495+06	4	15	10	quiz	69
177	f	2025-04-14 00:30:16.329053+06	5	19	10	quiz	69
178	f	2025-04-14 00:30:16.347001+06	6	24	10	quiz	69
179	f	2025-04-14 01:40:22.248257+06	3	10	10	quiz	71
180	f	2025-04-14 01:40:22.267793+06	4	15	10	quiz	71
181	f	2025-04-14 01:40:22.281028+06	5	19	10	quiz	71
182	f	2025-04-14 01:40:22.294114+06	6	24	10	quiz	71
183	f	2025-04-14 01:41:35.255154+06	3	10	10	quiz	71
184	f	2025-04-14 01:41:35.268372+06	4	15	10	quiz	71
185	f	2025-04-14 01:41:35.308974+06	5	19	10	quiz	71
186	f	2025-04-14 01:41:35.320218+06	6	24	10	quiz	71
187	f	2025-04-14 01:43:10.642519+06	1	3	10	quiz	71
188	t	2025-04-14 23:11:08.526542+06	10	37	10	practice	\N
\.


--
-- TOC entry 3619 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 3620 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 3621 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- TOC entry 3622 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 3623 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- TOC entry 3624 (class 0 OID 0)
-- Dependencies: 215
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 29, true);


--
-- TOC entry 3625 (class 0 OID 0)
-- Dependencies: 229
-- Name: quiz_choices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_choices_id_seq', 72, true);


--
-- TOC entry 3626 (class 0 OID 0)
-- Dependencies: 231
-- Name: quiz_question_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_question_category_id_seq', 10, true);


--
-- TOC entry 3627 (class 0 OID 0)
-- Dependencies: 233
-- Name: quiz_questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_questions_id_seq', 18, true);


--
-- TOC entry 3628 (class 0 OID 0)
-- Dependencies: 240
-- Name: quiz_quiz_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_quiz_categories_id_seq', 5, true);


--
-- TOC entry 3629 (class 0 OID 0)
-- Dependencies: 238
-- Name: quiz_quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_quiz_id_seq', 2, true);


--
-- TOC entry 3630 (class 0 OID 0)
-- Dependencies: 242
-- Name: quiz_quizsession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_quizsession_id_seq', 71, true);


--
-- TOC entry 3631 (class 0 OID 0)
-- Dependencies: 244
-- Name: quiz_quizsessionquestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_quizsessionquestion_id_seq', 218, true);


--
-- TOC entry 3632 (class 0 OID 0)
-- Dependencies: 217
-- Name: quiz_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_users_id_seq', 24, true);


--
-- TOC entry 3633 (class 0 OID 0)
-- Dependencies: 235
-- Name: quiz_usersolutions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_usersolutions_id_seq', 188, true);


--
-- TOC entry 3380 (class 2606 OID 42328)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3385 (class 2606 OID 42314)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3388 (class 2606 OID 42303)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3382 (class 2606 OID 42295)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3375 (class 2606 OID 42305)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3377 (class 2606 OID 42289)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3371 (class 2606 OID 42271)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3366 (class 2606 OID 42262)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3368 (class 2606 OID 42260)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3359 (class 2606 OID 42245)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3405 (class 2606 OID 42396)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3390 (class 2606 OID 42337)
-- Name: quiz_choices quiz_choices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_choices
    ADD CONSTRAINT quiz_choices_pkey PRIMARY KEY (id);


--
-- TOC entry 3393 (class 2606 OID 42345)
-- Name: quiz_question_category quiz_question_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_question_category
    ADD CONSTRAINT quiz_question_category_pkey PRIMARY KEY (id);


--
-- TOC entry 3396 (class 2606 OID 42353)
-- Name: quiz_questions quiz_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_pkey PRIMARY KEY (id);


--
-- TOC entry 3410 (class 2606 OID 50766)
-- Name: quiz_info_categories quiz_quiz_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_info_categories
    ADD CONSTRAINT quiz_quiz_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3414 (class 2606 OID 50768)
-- Name: quiz_info_categories quiz_quiz_categories_quiz_id_question_category_id_0660f50b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_info_categories
    ADD CONSTRAINT quiz_quiz_categories_quiz_id_question_category_id_0660f50b_uniq UNIQUE (quiz_id, question_category_id);


--
-- TOC entry 3408 (class 2606 OID 50760)
-- Name: quiz_info quiz_quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_info
    ADD CONSTRAINT quiz_quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 3416 (class 2606 OID 50786)
-- Name: quiz_quizsession quiz_quizsession_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_quizsession
    ADD CONSTRAINT quiz_quizsession_pkey PRIMARY KEY (id);


--
-- TOC entry 3420 (class 2606 OID 50792)
-- Name: quiz_quizsessionquestion quiz_quizsessionquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_quizsessionquestion
    ADD CONSTRAINT quiz_quizsessionquestion_pkey PRIMARY KEY (id);


--
-- TOC entry 3362 (class 2606 OID 42563)
-- Name: quiz_users quiz_users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_users
    ADD CONSTRAINT quiz_users_email_key UNIQUE (email);


--
-- TOC entry 3364 (class 2606 OID 42251)
-- Name: quiz_users quiz_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_users
    ADD CONSTRAINT quiz_users_pkey PRIMARY KEY (id);


--
-- TOC entry 3398 (class 2606 OID 42359)
-- Name: quiz_usersolutions quiz_usersolutions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_usersolutions
    ADD CONSTRAINT quiz_usersolutions_pkey PRIMARY KEY (id);


--
-- TOC entry 3378 (class 1259 OID 42329)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3383 (class 1259 OID 42325)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3386 (class 1259 OID 42326)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3373 (class 1259 OID 42311)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3369 (class 1259 OID 42282)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3372 (class 1259 OID 42283)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3403 (class 1259 OID 42398)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3406 (class 1259 OID 42397)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3391 (class 1259 OID 42389)
-- Name: quiz_choices_question_id_91499dec; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_choices_question_id_91499dec ON public.quiz_choices USING btree (question_id);


--
-- TOC entry 3394 (class 1259 OID 42370)
-- Name: quiz_questions_category_id_a6061467; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_questions_category_id_a6061467 ON public.quiz_questions USING btree (category_id);


--
-- TOC entry 3411 (class 1259 OID 50780)
-- Name: quiz_quiz_categories_question_category_id_5f0005e5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_quiz_categories_question_category_id_5f0005e5 ON public.quiz_info_categories USING btree (question_category_id);


--
-- TOC entry 3412 (class 1259 OID 50779)
-- Name: quiz_quiz_categories_quiz_id_4c68732f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_quiz_categories_quiz_id_4c68732f ON public.quiz_info_categories USING btree (quiz_id);


--
-- TOC entry 3417 (class 1259 OID 50815)
-- Name: quiz_quizsession_quiz_id_id_3252d910; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_quizsession_quiz_id_id_3252d910 ON public.quiz_quizsession USING btree (quiz_id_id);


--
-- TOC entry 3418 (class 1259 OID 50816)
-- Name: quiz_quizsession_user_id_189bbd7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_quizsession_user_id_189bbd7d ON public.quiz_quizsession USING btree (user_id);


--
-- TOC entry 3421 (class 1259 OID 50813)
-- Name: quiz_quizsessionquestion_questions_id_45de61b4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_quizsessionquestion_questions_id_45de61b4 ON public.quiz_quizsessionquestion USING btree (questions_id);


--
-- TOC entry 3422 (class 1259 OID 50814)
-- Name: quiz_quizsessionquestion_quiz_session_id_ede2b4f0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_quizsessionquestion_quiz_session_id_ede2b4f0 ON public.quiz_quizsessionquestion USING btree (quiz_session_id);


--
-- TOC entry 3360 (class 1259 OID 42564)
-- Name: quiz_users_email_54010888_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_users_email_54010888_like ON public.quiz_users USING btree (email varchar_pattern_ops);


--
-- TOC entry 3399 (class 1259 OID 42386)
-- Name: quiz_usersolutions_question_id_9ed283ac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_usersolutions_question_id_9ed283ac ON public.quiz_usersolutions USING btree (question_id);


--
-- TOC entry 3400 (class 1259 OID 50824)
-- Name: quiz_usersolutions_quiz_session_id_06ebf55e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_usersolutions_quiz_session_id_06ebf55e ON public.quiz_usersolutions USING btree (quiz_session_id);


--
-- TOC entry 3401 (class 1259 OID 42387)
-- Name: quiz_usersolutions_selected_answer_id_f5b9f47c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_usersolutions_selected_answer_id_f5b9f47c ON public.quiz_usersolutions USING btree (selected_answer_id);


--
-- TOC entry 3402 (class 1259 OID 42388)
-- Name: quiz_usersolutions_user_id_6856aa3f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX quiz_usersolutions_user_id_6856aa3f ON public.quiz_usersolutions USING btree (user_id);


--
-- TOC entry 3426 (class 2606 OID 42320)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3427 (class 2606 OID 42315)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3425 (class 2606 OID 42306)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3423 (class 2606 OID 42272)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3424 (class 2606 OID 42277)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_quiz_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_quiz_users_id FOREIGN KEY (user_id) REFERENCES public.quiz_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3428 (class 2606 OID 42360)
-- Name: quiz_choices quiz_choices_question_id_91499dec_fk_quiz_questions_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_choices
    ADD CONSTRAINT quiz_choices_question_id_91499dec_fk_quiz_questions_id FOREIGN KEY (question_id) REFERENCES public.quiz_questions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3429 (class 2606 OID 42365)
-- Name: quiz_questions quiz_questions_category_id_a6061467_fk_quiz_ques; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_category_id_a6061467_fk_quiz_ques FOREIGN KEY (category_id) REFERENCES public.quiz_question_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3434 (class 2606 OID 50774)
-- Name: quiz_info_categories quiz_quiz_categories_question_category_id_5f0005e5_fk_quiz_ques; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_info_categories
    ADD CONSTRAINT quiz_quiz_categories_question_category_id_5f0005e5_fk_quiz_ques FOREIGN KEY (question_category_id) REFERENCES public.quiz_question_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3435 (class 2606 OID 50769)
-- Name: quiz_info_categories quiz_quiz_categories_quiz_id_4c68732f_fk_quiz_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_info_categories
    ADD CONSTRAINT quiz_quiz_categories_quiz_id_4c68732f_fk_quiz_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.quiz_info(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3436 (class 2606 OID 50793)
-- Name: quiz_quizsession quiz_quizsession_quiz_id_id_3252d910_fk_quiz_info_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_quizsession
    ADD CONSTRAINT quiz_quizsession_quiz_id_id_3252d910_fk_quiz_info_id FOREIGN KEY (quiz_id_id) REFERENCES public.quiz_info(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3437 (class 2606 OID 50798)
-- Name: quiz_quizsession quiz_quizsession_user_id_189bbd7d_fk_quiz_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_quizsession
    ADD CONSTRAINT quiz_quizsession_user_id_189bbd7d_fk_quiz_users_id FOREIGN KEY (user_id) REFERENCES public.quiz_users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3438 (class 2606 OID 50803)
-- Name: quiz_quizsessionquestion quiz_quizsessionques_questions_id_45de61b4_fk_quiz_ques; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_quizsessionquestion
    ADD CONSTRAINT quiz_quizsessionques_questions_id_45de61b4_fk_quiz_ques FOREIGN KEY (questions_id) REFERENCES public.quiz_questions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3439 (class 2606 OID 50808)
-- Name: quiz_quizsessionquestion quiz_quizsessionques_quiz_session_id_ede2b4f0_fk_quiz_quiz; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_quizsessionquestion
    ADD CONSTRAINT quiz_quizsessionques_quiz_session_id_ede2b4f0_fk_quiz_quiz FOREIGN KEY (quiz_session_id) REFERENCES public.quiz_quizsession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3430 (class 2606 OID 42371)
-- Name: quiz_usersolutions quiz_usersolutions_question_id_9ed283ac_fk_quiz_questions_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_usersolutions
    ADD CONSTRAINT quiz_usersolutions_question_id_9ed283ac_fk_quiz_questions_id FOREIGN KEY (question_id) REFERENCES public.quiz_questions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3431 (class 2606 OID 50819)
-- Name: quiz_usersolutions quiz_usersolutions_quiz_session_id_06ebf55e_fk_quiz_quiz; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_usersolutions
    ADD CONSTRAINT quiz_usersolutions_quiz_session_id_06ebf55e_fk_quiz_quiz FOREIGN KEY (quiz_session_id) REFERENCES public.quiz_quizsession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3432 (class 2606 OID 42376)
-- Name: quiz_usersolutions quiz_usersolutions_selected_answer_id_f5b9f47c_fk_quiz_choi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_usersolutions
    ADD CONSTRAINT quiz_usersolutions_selected_answer_id_f5b9f47c_fk_quiz_choi FOREIGN KEY (selected_answer_id) REFERENCES public.quiz_choices(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3433 (class 2606 OID 42381)
-- Name: quiz_usersolutions quiz_usersolutions_user_id_6856aa3f_fk_quiz_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_usersolutions
    ADD CONSTRAINT quiz_usersolutions_user_id_6856aa3f_fk_quiz_users_id FOREIGN KEY (user_id) REFERENCES public.quiz_users(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-04-15 00:01:18 +06

--
-- PostgreSQL database dump complete
--

