name: Hello CI

on:
  push:
    branches:
      - phase-5_scalibility_optimization

jobs:
  setup-install:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set env variables
        run: |
          echo "DB_NAME=db_name" >> .env
          echo "DB_USER=db_user" >> .env
          echo "DB_PASSWORD=test_password" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DJANGO_Scrt_KEY=secret-key" >> .env
          
      - name: Apply migration
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate

      - name: Rune tests
        run:  |
          pytest